### ISSUE TITLE
Set MIX_ENV=test

### ISSUE THREAD

**Issue by ckruse** [tomekowal/flycheck-mix#6]
Hey,

is there a way to set `MIX_ENV=test` for the `mix compile` command? Running it for `MIX_ENV=dev` breaks code reloading for phoenix.

Best regards,
 CK

**Comment by ckruse** [comment]
Ok, I ended up doing this:

~~~ elisp
(add-hook 'flycheck-before-syntax-check-hook (lambda ()
                                                 (when (string-equal major-mode "elixir-mode")
                                                   (setenv "MIX_ENV" "test"))))
~~~

This seems to work. I leave this issue open, maybe it is worth a note in the readme?

**Comment by tomekowal** [comment]
I am not sure what to do with it TBH. How does it break the code reloading? The package tries to run `mix compile` and return any errors. Does running `mix compile` with default `dev` env break the code reloading?

**Comment by ckruse** [comment]
Yes, it does. Phoenix code reloading checks ctime/mtime to decide if code has to be recompiled. mix compile messes with that. Running mix compile with MIX_ENV=test circumvents this problem.

**Comment by ckruse** [comment]
See https://github.com/phoenixframework/phoenix/issues/1165#issuecomment-136055673 for an explanation by Chris McCord

**Comment by tomekowal** [comment]
Thanks for the link. That clarifies a lot. I’ll schedule some time in the weekend to fix the issue!

**Comment by tomekowal** [comment]
@ckruse I've put `MIX_ENV=test` before the command, and it now compiles for the `test` env. It should prevent braking tests. Thanks again for the report!

**Comment by ckruse** [comment]
Great! Thank you very much!
