### ISSUE TITLE
Executable not found

### ISSUE THREAD

**Issue by gabrielelana** [tomekowal/flycheck-mix#7]
For me the last commit (0bc301c) breaks flycheck because `flycheck-define-checker` will use the first element of the `:command` list to identify the executable which should be `elixir` but right now is `MIX_ENV=test`

I tried to `(setq flycheck-elixir-mix-executable "elixir")` but without success ("No file named elixir" which is weird) 

[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

**Comment by tomekowal** [comment]
Thanks for the report. I'll look into it during the weekend.

**Comment by tomekowal** [comment]
Hey, @gabrielelana I believe everything should work now.
I decided to start `Mix` and set it to `:test` in the `elixir -e ...` section.
This way I don't have to pass env vars anywhere.
I am closing the issue but feel free to reopen it if something still doesn't work or open another one if I broke something else with that change.
Thanks again for report and patience :)
